# Export a compact Markdown summary from the current Ghidra program.
# @author NingWen2000
# @category ReverseHelper
# @keybinding
# @menupath Tools.ReverseHelper.Export Analysis Report
# @toolbar


target = askFile("Save ReverseHelper Ghidra report", "Save")
listing = currentProgram.getListing()
function_manager = currentProgram.getFunctionManager()
memory = currentProgram.getMemory()

lines = [
    "# Ghidra Analysis Summary",
    "",
    "- Program: `%s`" % currentProgram.getName(),
    "- Language: `%s`" % currentProgram.getLanguageID(),
    "- Image base: `%s`" % currentProgram.getImageBase(),
    "- Minimum address: `%s`" % currentProgram.getMinAddress(),
    "- Maximum address: `%s`" % currentProgram.getMaxAddress(),
    "",
    "## Memory blocks",
    "",
    "| Name | Start | End | R | W | X |",
    "|---|---|---|:---:|:---:|:---:|",
]

for block in memory.getBlocks():
    lines.append("| `%s` | %s | %s | %s | %s | %s |" % (
        block.getName(), block.getStart(), block.getEnd(),
        "Y" if block.isRead() else "-", "Y" if block.isWrite() else "-", "Y" if block.isExecute() else "-"))

lines.extend(["", "## Functions", ""])
iterator = function_manager.getFunctions(True)
count = 0
while iterator.hasNext() and not monitor.isCancelled():
    function = iterator.next()
    lines.append("- `%s` at `%s`" % (function.getName(), function.getEntryPoint()))
    count += 1

lines.extend(["", "Total functions: %d" % count, "", "> Generated by ReverseHelper Ghidra scripts.", ""])
writer = open(str(target), "w")
try:
    writer.write("\n".join(lines))
finally:
    writer.close()

println("ReverseHelper report written to %s" % target)
